import PDFDocument from "pdfkit";
import { prisma } from "../server";

export class ReportService {
  static async generateMonthlyWellnessReport(userId: string, month: number, year: number) {
    const startDate = new Date(year, month - 1, 1);
    const endDate = new Date(year, month, 0);
    const [moodLogs, productivityLogs, journalEntries, insights] = await Promise.all([
      prisma.moodLog.findMany({ where: { userId, date: { gte: startDate, lte: endDate } } }),
      prisma.productivityLog.findMany({ where: { userId, date: { gte: startDate, lte: endDate } } }),
      prisma.journalEntry.findMany({ where: { userId, createdAt: { gte: startDate, lte: endDate } }, include: { aiAnalysis: true } }),
      prisma.aIInsight.findMany({ where: { userId, generatedAt: { gte: startDate, lte: endDate } } }),
    ]);

    const avgMood = moodLogs.length > 0 ? moodLogs.reduce((s, l) => s + l.mood, 0) / moodLogs.length : 0;
    const avgStress = moodLogs.length > 0 ? moodLogs.reduce((s, l) => s + l.stress, 0) / moodLogs.length : 0;
    const avgEnergy = moodLogs.length > 0 ? moodLogs.reduce((s, l) => s + l.energy, 0) / moodLogs.length : 0;
    const avgSleep = moodLogs.filter((l) => l.sleepHours).reduce((s, l) => s + (l.sleepHours || 0), 0) / moodLogs.filter((l) => l.sleepHours).length || 0;
    const exerciseDays = moodLogs.filter((l) => l.exercise).length;

    return {
      period: `${startDate.toLocaleString("default", { month: "long" })} ${year}`,
      summary: {
        avgMood: avgMood.toFixed(1), avgStress: avgStress.toFixed(1),
        avgEnergy: avgEnergy.toFixed(1), avgSleep: avgSleep.toFixed(1),
        exerciseDays, journalCount: journalEntries.length, totalEntries: moodLogs.length,
      },
      insights: insights.map((i) => ({ title: i.title, description: i.description })),
    };
  }

  static async generatePDFReport(userId: string, reportData: any): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument();
      const chunks: Buffer[] = [];
      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);
      doc.fontSize(24).text("MindSync Wellness Report", 50, 50);
      doc.fontSize(12).text(`Period: ${reportData.period}`, 50, 90);
      doc.moveDown();
      doc.fontSize(16).text("Summary", 50, 130);
      doc.fontSize(12);
      doc.text(`Average Mood: ${reportData.summary.avgMood}/10`);
      doc.text(`Average Stress: ${reportData.summary.avgStress}/10`);
      doc.text(`Average Energy: ${reportData.summary.avgEnergy}/10`);
      doc.text(`Average Sleep: ${reportData.summary.avgSleep} hours`);
      doc.text(`Exercise Days: ${reportData.summary.exerciseDays}`);
      doc.text(`Journal Entries: ${reportData.summary.journalCount}`);
      doc.moveDown();
      doc.fontSize(16).text("AI Insights");
      doc.fontSize(12);
      reportData.insights.forEach((insight: any, i: number) => {
        doc.text(`${i + 1}. ${insight.title}`);
        doc.text(`   ${insight.description}`, { indent: 20 });
      });
      doc.fontSize(10).text("\nThis report is generated by MindSync AI and is not a medical diagnosis.", 50, doc.page.height - 100);
      doc.end();
    });
  }

  static generateCSVReport(data: any[]): string {
    if (data.length === 0) return "";
    const headers = Object.keys(data[0]).join(",");
    const rows = data.map((row) => Object.values(row).map((val) => `"${String(val ?? "").replace(/"/g, '""')}"`).join(","));
    return [headers, ...rows].join("\n");
  }
}
