import { Router } from "express";
import { AuthController } from "../controllers/auth.controller";
import { authenticate } from "../middleware/auth";
const router = Router();
router.post("/register", AuthController.register);
router.post("/login", AuthController.login);
router.post("/refresh", AuthController.refresh);
router.get("/me", authenticate, AuthController.me);
router.patch("/profile", authenticate, AuthController.updateProfile);
router.post("/logout", authenticate, AuthController.logout);
export default router;
